### ISSUE TITLE
QC Table 3 state flags

### ISSUE THREAD

**Issue by Mark-Rogers** [returncode13/Scar#39]
QC Table are not performing 3 state toggle

The QC flags are not operating as a 3 state system

“Undefined”, “Good” and “Bad”

We said that we wanted to a single button toggle to circle around these three states in order.  This is not happening.  You only have “ON” and “OFF”, a restriction due to the storage of the QC table value as a BOOLEAN

 ![snip](https://user-images.githubusercontent.com/20038950/32627945-557fca18-c57b-11e7-8632-d3e30fc47575.PNG)

( Note also that the “headers_fk” is superfluous (Not normalized can be cause of inconsistencies).  The qc matrix points to the sessiondetails_fk, which points to the jobstep.  We only have one QC table per job step, not per volume.)

Here is some background reading on 3VL wiki/Three-valued_logic

Alternatively (less efficiently) you could achieve with a signed integer: 1=good, 0=undefined, -1=bad

              Toggle                          toggle button adds 1
                                                   If new_value =2 then set to new_value =-1

            Sequence summary       in order second logic overrides first:
                                                            If any subline value =0 then sequence value =0
                                                            If any subline value =-1 then sequence value =-1

Marking a sequence as “good” already marks all the sublines “good”.  That’s good.
I think the same should apply when toggling the sequence flag through to other states.  Doesn’t seem to currently.

**Comment by Mark-Rogers** [comment]
We decided that history of QC status changes would not be a requirement

**Comment by returncode13** [comment]
fixed in #83

**Comment by returncode13** [comment]
The check values are not been saved in the database.

**Comment by returncode13** [comment]
The issue was only for the segdLoad nodes. Fixed in #86
