### ISSUE TITLE
QC Table [Q] Button

### ISSUE THREAD

**Issue by Mark-Rogers** [returncode13/Scar#41]
I would like a bit more flexibility in the behavior of the [Q] button on the nodes.

Currently, where the matrix is undefined for that node, the dialogue opens to choose/add qc types.  Thereafter the same button opens the QC table, and there is no opportunity to modify the qc matrix.  Although I can see dangers in allowing deletion of fields, people will certainly be wanting to ADD qc to a jobstep all the time.

May I suggest you proceed something like this:

![capture](https://user-images.githubusercontent.com/20038950/32628377-c901136a-c57c-11e7-99f8-d44c0b0dc502.PNG)

Have the [Q] button ALWAYS mean setup/change the QC matrix for this node

•	When I “add a type” you should automatically add that to the qctype table (whether or not it gets ticked)
•	The ticked items get added to the qc matrix table

Use the “present Boolean” in the qc matrix to further determine whether a qc gets displayed.  I think this value could be used as a “temporary delete” mechanism.  Initially they will all be “TRUE”

•	If on another occasion the qc gets unticked
    i.	the Boolean is changed to “FALSE”.  
    ii.	No QCtable data in the database is deleted it is just not displayed.
•	If on a third occasion the qc is re-instated, the values are already in the QCtable in the database and re-appear
•	A new QC type can be added to the matrix at any time without any bad effects.

![capture2](https://user-images.githubusercontent.com/20038950/32628392-d7da2e6c-c57c-11e7-8d90-55ee5afebb3e.PNG)

Put a new Q button, maybe here, next to the “T” and the “H”.  Which opens the QC table.  

==========================

In addition we should be given opportunity to rename a qctype

**Comment by returncode13** [comment]
fixed in #81
