### ISSUE TITLE
Summary Algorithm Performance

### ISSUE THREAD

**Issue by Mark-Rogers** [returncode13/Scar#50]
I think you must find a way to recalculating the entire table every time.

•	Store a timestamp of the last time the summary table was calculated
•	Every time there is any alteration to the status of any property associated with a subline (header, log, QC etc) update a timestamp for that subline.
•	Update and propogate from those sublines only

Hopefully you have other ideas too to improve it!

**Comment by Mark-Rogers** [comment]
this also needs to be multi-threaded in the background with a whirring clock somewhere

**Comment by returncode13** [comment]
The database should know when information pertaining to a node has been updated.

Only perform walks starting from places where the database shows changes

**Comment by returncode13** [comment]
OR add two columns to all tables

if "time updated" > "time summarized"

the you need to update summary walk

**Comment by returncode13** [comment]
fixed in #79
