### ISSUE TITLE
SEGD load node.  Insight v & log

### ISSUE THREAD

**Issue by Mark-Rogers** [returncode13/Scar#64]
If you look in the dugio volume directory created by the offline SEGD load you will see a “logs” subdirectory.

For example

/naila/contracts/nai044217-cgg-kanazawa_3d/nai044217-PROD/loadedData/
KANAZAWA_NAVMERGE/000scratch/outputs/KANAZAWA_NavMerge_TidalHeaders/
KANAZAWA_NavMerge_TidalHeaders.dugio/logs

In which we have

            runHistory.txt    which gives you the Insight version each attempt at each sequence was run with
            dunav.log         Also gives you merge summary report

I haven’t found anyway of getting run parameters used for each line yet.  But this is a start

**Comment by returncode13** [comment]
information from logs collected in #82 .
LogStatusWatcher to be implemented for volume type=2
WorkflowWatcher to be implemented for volume type=2

**Comment by returncode13** [comment]
fixed in #84
